---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
<<<<<<< HEAD
<<<<<<< HEAD
       url: http://13.126.60.229:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife&p=war&v=LATEST
=======
       url: http://65.1.64.216:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife&p=war&v=LATEST
>>>>>>> 3720fc23a2b108e80eca96dd19a21044ab5a9eac
=======
       url: http://65.1.64.216:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife&p=war&v=LATEST
>>>>>>> 0eacb6749353746503fb3b2b9189d5352ef889b2
       dest: /usr/share/tomcat/webapps/gameoflife.war
  - name: Start Tomcat
    service: name=tomcat state=started
